Repository fastcampus-febe/TeamA-BE, pull requests merged in 2023-01, with the labels that each got.

#2 1 - 프로젝트생성
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/travel/TravelApplication.java
  src/main/java/com/example/travel/aop/AuthAspect.java
  src/main/java/com/example/travel/aop/LogAdvice.java
  src/main/java/com/example/travel/config/SwaggerConfig.java
  src/main/java/com/example/travel/config/WebSecurityConfig.java
  src/main/java/com/example/travel/controller/MemberController.java
  src/main/java/com/example/travel/controller/PageController.java
  src/main/java/com/example/travel/dto/TokenDto.java
  src/main/java/com/example/travel/dto/UserDto.java
  src/main/java/com/example/travel/entity/User.java
  src/main/java/com/example/travel/ext/JwtAuthenticationFilter.java
  src/main/java/com/example/travel/ext/JwtProperties.java
  src/main/java/com/example/travel/ext/JwtTokenProvider.java
  src/main/java/com/example/travel/repository/UserRepository.java
  src/main/java/com/example/travel/service/UserService.java
  src/main/java/com/example/travel/util/Pagination.java
  src/main/java/com/example/travel/util/SearchDto.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/test/java/com/example/travel/TravelApplicationTests.java
Labels: enhancement

#12 11 - 게시판 페이지로 이동
  src/main/java/com/example/travel/controller/PageController.java
Labels: enhancement

#14 13 - AWS 배포
  appspec.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
Labels: enhancement

#16 14 - Gradle 수정
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/misc.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: bug

#18 18 - Board추가
  src/main/java/com/example/travel/controller/BoardController.java
  src/main/java/com/example/travel/dto/BoardRequestDto.java
  src/main/java/com/example/travel/dto/BoardResponseDto.java
  src/main/java/com/example/travel/entity/Board.java
  src/main/java/com/example/travel/entity/Comment.java
  src/main/java/com/example/travel/exception/CustomException.java
  src/main/java/com/example/travel/exception/ErrorCode.java
  src/main/java/com/example/travel/exception/ErrorResponse.java
  src/main/java/com/example/travel/exception/GlobalExceptionHandler.java
  src/main/java/com/example/travel/repository/BoardRepository.java
  src/main/java/com/example/travel/service/BoardService.java
  src/test/java/com/example/travel/controller/BoardControllerTest.java
Labels: enhancement

#20 #19 - 게시판 > 상세 게시글 내용 가져오기
  src/main/java/com/example/travel/config/WebSecurityConfig.java
  src/main/java/com/example/travel/controller/BoardController.java
  src/main/java/com/example/travel/service/BoardService.java
  src/test/java/com/example/travel/controller/BoardControllerTest.java
Labels: enhancement

#21 21 - 게시글 조회, 작성, 수정
  src/main/java/com/example/travel/entity/Board.java
  src/main/java/com/example/travel/service/BoardService.java
  src/main/resources/application.properties
Labels: duplicate

#25 #22-deleteBoard
  src/main/java/com/example/travel/controller/BoardController.java
  src/main/java/com/example/travel/service/BoardService.java
  src/test/java/com/example/travel/controller/BoardControllerTest.java
Labels: enhancement

#26 26 - 좋아요 및 조회수
  src/main/java/com/example/travel/controller/BoardController.java
  src/main/java/com/example/travel/dto/BoardRequestDto.java
  src/main/java/com/example/travel/dto/BoardResponseDto.java
  src/main/java/com/example/travel/entity/Board.java
  src/main/java/com/example/travel/entity/Member.java
  src/main/java/com/example/travel/entity/Thumb.java
  src/main/java/com/example/travel/repository/ThumbRepository.java
  src/main/java/com/example/travel/service/BoardService.java
  src/test/java/com/example/travel/controller/BoardControllerTest.java
Labels: enhancement

#29 #27,#28 - create_date 에 따라 게시글 정렬해서 가져오기, 게시글 좋아요 처리
  src/main/java/com/example/travel/config/WebSecurityConfig.java
  src/main/java/com/example/travel/controller/BoardController.java
  src/main/java/com/example/travel/entity/Board.java
  src/main/java/com/example/travel/service/BoardService.java
Labels: enhancement

#30 30 - Entity수정
  src/main/java/com/example/travel/entity/Board.java
  src/main/java/com/example/travel/entity/Comment.java
Labels: enhancement

#31 CommentDTO 추가
  src/main/java/com/example/travel/dto/BoardResponseDto.java
  src/main/java/com/example/travel/dto/CommentRequestDto.java
  src/main/java/com/example/travel/dto/CommentResponseDto.java
  src/main/java/com/example/travel/entity/Comment.java
  src/main/java/com/example/travel/repository/CommentRepository.java
Labels: enhancement

#32 32 - 댓글CRUD
  src/main/java/com/example/travel/controller/BoardController.java
  src/main/java/com/example/travel/controller/CommentController.java
  src/main/java/com/example/travel/dto/BoardRequestDto.java
  src/main/java/com/example/travel/dto/BoardResponseDto.java
  src/main/java/com/example/travel/dto/CommentRequestDto.java
  src/main/java/com/example/travel/dto/CommentResponseDto.java
  src/main/java/com/example/travel/entity/Board.java
  src/main/java/com/example/travel/entity/Comment.java
  src/main/java/com/example/travel/entity/Thumb.java
  src/main/java/com/example/travel/repository/BoardRepository.java
  src/main/java/com/example/travel/repository/MemberRepository.java
  src/main/java/com/example/travel/service/BoardService.java
  src/main/java/com/example/travel/service/CommentService.java
Labels: enhancement

#35 Feature/33 검색기능구현
  .gradle/7.6/executionHistory/executionHistory.lock
  .idea/compiler.xml
  src/main/java/com/example/travel/controller/BoardController.java
  src/main/java/com/example/travel/repository/BoardRepository.java
  src/main/java/com/example/travel/service/BoardService.java
  src/main/resources/application.properties
Labels: enhancement

#37 36 - 게시판오류수정
  src/main/java/com/example/travel/controller/BoardController.java
  src/main/java/com/example/travel/service/BoardService.java
Labels: bug

#38 #33-게시글 좋아요 순으로 정렬
  src/main/java/com/example/travel/controller/BoardController.java
  src/main/java/com/example/travel/service/BoardService.java
Labels: enhancement

#39 #36-댓글 작성 시 writer 컬럼에 nickname 저장되도록 수정.
  src/main/java/com/example/travel/service/CommentService.java
Labels: bug, enhancement

#41 40 - 주석오류
  src/main/java/com/example/travel/service/BoardService.java
Labels: bug

#43 41 - test파일어노테이션삭제
  src/test/java/com/example/travel/TravelApplicationTests.java
  src/test/java/com/example/travel/controller/BoardControllerTest.java
Labels: bug

#45 45 - findAllByWriterContaining
  src/main/java/com/example/travel/repository/BoardRepository.java
  src/main/java/com/example/travel/service/BoardService.java
Labels: enhancement

#46 46 - BoardWriter
  src/main/java/com/example/travel/dto/BoardResponseDto.java
  src/main/java/com/example/travel/service/BoardService.java
Labels: bug
